FROM docker.io/library/debian:latest as builder

RUN apt update && apt install -y golang ca-certificates

COPY . /source

RUN cd /source && go build -o /j7s-gitea-push-listener cmd/j7s-gitea-push-listener/main.go

FROM docker.io/library/debian:latest
RUN apt update && apt install -y ca-certificates
COPY --from=builder /j7s-gitea-push-listener /j7s-gitea-push-listener

